name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # Explicit runner version
    env:
      ANDROID_HOME: ${{ github.workspace }}/Android
      PATH: ${{ github.workspace }}/Android/cmdline-tools/latest/bin:${{ github.workspace }}/Android/platform-tools:$PATH

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full Git clone to avoid tar
        clean: true     # Remove any leftover files
        lfs: false

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y tar build-essential git python3-pip python3-dev ffmpeg \
        libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
        unzip wget openjdk-11-jdk

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache Buildozer and Python packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/Android
        key: ${{ runner.os }}-android-sdk

    - name: Install Android SDK and Build Tools
      run: |
        if [ ! -d "$ANDROID_HOME/cmdline-tools/latest" ]; then
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
        fi

    - name: Install Buildozer
      run: pip install --upgrade cython buildozer

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MaduraiMess-apk
        path: bin/*.apk
