name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'  # or 'temurin', 'corretto', etc.
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev python3-setuptools git
        sudo apt-get install -y libncurses5-dev libffi-dev libssl-dev
        sudo apt-get install -y openjdk-11-jdk  # Additional Java install for AIDL
        sudo apt-get install -y android-sdk android-sdk-platform-tools
        pip install virtualenv kivy buildozer cython python-for-android

        # Set Android SDK path (may need adjustment based on your setup)
        echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV

    - name: Check for buildozer.spec
      id: check_spec
      run: |
        if [ -f "buildozer.spec" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Initialize Buildozer (if needed)
      if: steps.check_spec.outputs.exists == 'false'
      run: |
        buildozer init

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
