name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # or the version you need

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev python3-setuptools git
        sudo apt-get install -y libncurses5-dev libffi-dev libssl-dev
        pip install virtualenv kivy buildozer cython

        # Install Android SDK and build-tools
        sudo apt-get install -y android-sdk android-sdk-platform-tools android-sdk-build-tools

    - name: Check for buildozer.spec
      id: check_spec
      run: |
        if [ -f "buildozer.spec" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    - name: Build APK
      run: |
        buildozer -v android debug
        
