name: Android Build with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Python 3.10 works best with current Buildozer

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              openjdk-17-jdk \
              git \
              zip \
              unzip \
              zlib1g-dev \
              ccache \
              libncurses5 \
              libncursesw5

      - name: Install Buildozer and tools
        run: |
          pip install --upgrade pip wheel virtualenv
          pip install buildozer
          buildozer init
          buildozer android update

      - name: Create required directories
        run: |
          mkdir -p $HOME/.buildozer
          mkdir -p .buildozer/android/platform/python-for-android
          mkdir -p .buildozer/android/platform/build-arm64-v8a

      - name: Run Buildozer clean
        run: |
          buildozer android clean

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: madurai-mess-apk
          path: bin/*.apk
