name: Android Build with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/Android/Sdk
      PATH: ${{ github.workspace }}/Android/Sdk/cmdline-tools/latest/bin:${{ github.workspace }}/Android/Sdk/platform-tools:${{ github.workspace }}/Android/Sdk/build-tools/31.0.0:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full clone

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              openjdk-17-jdk \
              git \
              zip \
              unzip \
              zlib1g-dev \
              ccache \
              libncurses-dev \
              wget

      - name: Install Android SDK command-line tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip wheel virtualenv
          pip install buildozer cython

      - name: Create required directories
        run: |
          mkdir -p $HOME/.buildozer
          mkdir -p .buildozer/android/platform/python-for-android
          mkdir -p .buildozer/android/platform/build-arm64-v8a

      - name: Run Buildozer clean
        run: buildozer android clean

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: madurai-mess-apk
          path: bin/*.apk
